export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const NEW_USER = 'NEW_USER';
export const FETCH_MEN_PRODUCTS = 'FETCH_MEN_PRODUCTS';
export const FETCH_WOMEN_PRODUCTS = 'FETCH_WOMEN_PRODUCTS';
export const FETCH_KIDS_PRODUCTS = 'FETCH_KIDS_PRODUCTS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT  = 'USER_LOGIN';